jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t open-sign-server:latest -f apps/OpenSignServer/Dockerfile .

      # Step 4: Configure AWS credentials from OIDC Provider
      - name: Configure AWS credentials from OIDC Provider
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_PRODUCTION_ROLE }}  # IAM Role ARN to assume
          aws-region: ap-southeast-2  # AWS region (make sure this is correct)
          role-session-name: EFFI-GitHub-CI-CD-GitHub-Runner
          role-duration-seconds: 900  # Duration of the session (15 minutes)

      # Step 5: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
          skip-logout: false  # Ensures that login occurs correctly
          registry: 241924812472.dkr.ecr.ap-southeast-2.amazonaws.com  # Specify the correct registry explicitly

      # Step 6: Tag Docker image
      - name: Tag Docker image
        run: |
          IMAGE_TAG=latest
          REPOSITORY_URI=241924812472.dkr.ecr.ap-southeast-2.amazonaws.com/opensign-service-api-saas-production
          docker tag open-sign-server:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

      # Step 7: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          REPOSITORY_URI=241924812472.dkr.ecr.ap-southeast-2.amazonaws.com/opensign-service-api-saas-production
          docker push $REPOSITORY_URI:$IMAGE_TAG
