name: Backend-Deploy-Production-ECR

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  id-token: write  # Allow GitHub to issue an OIDC token for authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t open-sign-server:latest -f apps/OpenSignServer/Dockerfile .

      # Step 4: Configure AWS credentials from OIDC Provider
      - name: Configure AWS credentials from OIDC Provider
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::241924812472:role/EFFI-GITHUB-CICD-Role  # IAM Role ARN to assume
          aws-region: ${{ secrets.AWS_REGION }}  # AWS region (set as a secret)
          role-session-name: GitHub-CI-CD-Session  # Custom session name
          role-duration-seconds: 900  # Duration of the session (15 minutes)

      # Step 5: Log in to Amazon ECR (using version v2)
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2  # Use version 2
        with:
          registry-ids: 241924812472  # 12-digit AWS Account ID

      # Step 6: Tag Docker image for ECR
      - name: Tag Docker image
        run: |
          IMAGE_TAG=saas-production  # Tag that matches your task definition
          REPOSITORY_URI=241924812472.dkr.ecr.ap-southeast-2.amazonaws.com/opensign-service-api  # Correct repository name
          docker tag open-sign-server:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

      # Step 7: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=saas-production  # Tag that matches your task definition
          REPOSITORY_URI=241924812472.dkr.ecr.ap-southeast-2.amazonaws.com/opensign-service-api  # Correct repository name
          docker push $REPOSITORY_URI:$IMAGE_TAG
