name: OpenSign Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java (Maven)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Cache Maven dependencies (optional, speeds up the build)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project
      - name: Build with Maven
        run: |
          cd OpenSignServer  # Go to the OpenSignServer directory
          mvn clean install  # Run Maven build (you can also use `mvn verify` or `mvn package`)

      # Step 5: Run Tests (optional)
      - name: Run tests
        run: |
          cd OpenSignServer
          mvn test
